var bitcore = require('bitcore-lib');
var Mnemonic = require('bitcore-mnemonic');
var HDPrivateKey = bitcore.HDPrivateKey;
var mnemonic = new Mnemonic('scheme caution cabin snack squeeze busy lava duck bleak cement medal endless');
var hdPrivateKey = mnemonic.toHDPrivateKey();
exports.hdPrivateKey = hdPrivateKey;
var addressKey = hdPrivateKey.derive("m/44'/0'/0'/0/0");
var address = addressKey.privateKey.toAddress();
var accountKey = hdPrivateKey.derive("m/44'/0'/0'");
exports.accountKey = accountKey;
var requestKey = hdPrivateKey.derive("m/1'/0");
var entropySource = bitcore.crypto.Hash.sha256(requestKey.privateKey.toBuffer()).toString('hex');
exports.entropySource = entropySource;
console.log("Address privateKey: " + addressKey.privateKey.toWIF());
console.log("Address: " + address.toString());
console.log("Master HDPrivateKey: " + hdPrivateKey.toString());
console.log("Master HDPublicKey: " + hdPrivateKey.hdPublicKey.toString());
console.log("Account HDPublicKey: " + accountKey.hdPublicKey.toString());
console.log("entropySource: " + entropySource);
//# sourceMappingURL=HDPrivateKey.js.map